#+TITLE: m17n-ne
#+DESCRIPTION: ne-NP im varient for ibus-m17n
#+DATE: Friday, Dec 04 2015
#+STARTUP: showall

Nepali input method variant for ibus-m17n.

* How to install

  #+begin_src bash
    # make install
  #+end_src

  restart the *ibus* for changes to appear.

  #+begin_src bash
    $ ibus restart
  #+end_src

* Cross Map Hacks

  Since *ibus* runs =setxkbmap= in background, which alternative
  layout, is reset to *us* (qwerty).

  as they say:

  #+begin_quote
  *Go Away Or I Will Replace You With A Very Small Shell Script*
  #+end_quote

** How to install

   for now it only works for dvorak layout, see =hijack.sh= script to
   change to other layout. Here is back story of endeavor.

   #+begin_src bash
     # make hijack
   #+end_src

* About layouts

** lipi

*** Why ?

    - Romanized layout few symbol/punctuation unavailable, which results
      in constant switching

    - Vanilla Romanized isn't idiot proof

    - Romanized layout was designed for fixed layout.

*** Design

    Lipi (लिपि) is originally based on *nepali romanized layout* for
    reduce learning.

**** obvious completion

**** idiomatic completion

     | normally | improvements |
     |----------+--------------|
     | traa     | traa         |
