#+TITLE: m17n-ne
#+DESCRIPTION: ne-NP im varient for ibus-m17n
#+DATE: Friday, Dec 04 2015
#+STARTUP: showall

Nepali input method varient for ibus-m17n.

* How to install

  #+begin_src bash
    # make install
  #+end_src

  restart the *ibus* for changes to appear.

  restarting *ibus* from /command line/

  #+begin_src bash
    $ ibus restart
  #+end_src

* Cross Map Hacks

  Since *ibus* runs =setxkbmap= in background, which alternative
  layout, is reset to *us* (qwerty).

  as they say:

  #+begin_verse
  *Go Away Or I Will Replace You With A Very Small Shell Script*
  #+end_verse

** How to install

   for now it only works for dvorak layout, see =hijack.sh= script to
   change to other layout.

   #+begin_src bash
     # make hijack
   #+end_src

* History

  After the changes in =ibus= architecture from version =1.4= to
  =1.5=, it has been difficult for alternative layout users. We were
  left with very little choice either find the replacement or freeze
  the last workable version.

  As I froze my package for last 2 years, compatibility have slowely
  started to break as the new version of the ecosystem are rolled out.
  Fed up with unexpected application =core-dump= or temination, and
  Incompatiblity with =Gtk3.IBus= force me to update =ibus= without
  the avail solution.
